force-app/main/default/objects/Product2/fields/CEU_Amount__c.field-meta.xml
<CustomField>
    <fullName>CEU_Amount__c</fullName>
    <description>The amount of Continuing Education Unit&apos;s being offered for this course. Primary for professional education industries and approved by a sponsoring organization.</description>
    <inlineHelpText>The amount of Continuing Education Unit&apos;s being offered</inlineHelpText>
    <label>CEU Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_End_Date__c</fullName>
    <description>Date the Course Ends</description>
    <inlineHelpText>Date the Course Ends.  If Online (On Demand), leave blank</inlineHelpText>
    <label>Course End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Image__c.field-meta.xml
<CustomField>
    <fullName>Course_Image__c</fullName>
    <description>Image utilized for the Course Offering.  It may pull into the online website or store front</description>
    <inlineHelpText>Image utilized for the Course Offering.  It may pull into the online website or store front</inlineHelpText>
    <label>Course Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Course_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_Start_Date__c</fullName>
    <description>Date the Course Begins or the date that the course becomes available</description>
    <inlineHelpText>Date Course Begins or is available if a self-guided Course</inlineHelpText>
    <label>Course Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Featured_Course__c.field-meta.xml
<CustomField>
    <fullName>Featured_Course__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to identify if this is a featured course and it&apos;ll display as a primary course offering</description>
    <inlineHelpText>Set to true if the course should be one of the 3 featured courses on cape.stthomas.edu</inlineHelpText>
    <label>Featured Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <description>How is the class being administered.</description>
    <inlineHelpText>How the class is being administered.</inlineHelpText>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online: Self-Guided</fullName>
            </value>
            <value>
                <fullName>Online: Instructor-Guided</fullName>
            </value>
            <value>
                <fullName>Face-to-Face</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Retire_Date__c.field-meta.xml
<CustomField>
    <fullName>Retire_Date__c</fullName>
    <description>Date that it will no longer appear on the course catalog as an offering</description>
    <inlineHelpText>Date that it will no longer appear on the course catalog as an offering</inlineHelpText>
    <label>Retire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sponsoring_College_School__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_College_School__c</fullName>
    <description>What School is Sponsoring the course content</description>
    <inlineHelpText>School/College sponsoring the course content</inlineHelpText>
    <label>Sponsoring College/School</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>College of Arts &amp; Sciences</fullName>
            </value>
            <value>
                <fullName>Dougherty Family College</fullName>
            </value>
            <value>
                <fullName>Morrison College of Health</fullName>
            </value>
            <value>
                <fullName>Opus College of Business</fullName>
            </value>
            <value>
                <fullName>School of Divinity</fullName>
            </value>
            <value>
                <fullName>School of Education</fullName>
            </value>
            <value>
                <fullName>School of Engineering</fullName>
            </value>
            <value>
                <fullName>School of Law</fullName>
            </value>
            <value>
                <fullName>The Selim Center</fullName>
            </value>
            <value>
                <fullName>University of St. Thomas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start Time of the Course. If an On-Demand Course, Time may be blank</description>
    <inlineHelpText>Leave blank for Online (On Demand) Format.</inlineHelpText>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Storefront_Info_Page__c.field-meta.xml
<CustomField>
    <fullName>Storefront_Info_Page__c</fullName>
    <description>Link to the course Info Page or Storefront Page</description>
    <inlineHelpText>Link to the course Info Page or Storefront Page</inlineHelpText>
    <label>Storefront/Info Page</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/capeFeed.cls
// Copyright 2020 University of St. Thomas - Minnesota. All rights reserved.
// Use of this source code is governed by a BSD Revised
// license that can be found in the LICENSE file.
// Created by Thaddaeus Dahlberg on 07/07/2018.

@RestResource(urlMapping='/capefeed/*')

// https://stthomas.force.com/applicantportal/services/apexrest/capefeed?feedType=courselist

global with sharing class capeFeed {

    private static String feedType { get; set; }

    private Class capeItem {
        public String id { get; set; }
        public String title { get; set; }
        public String description { get; set; }
        public String link { get; set; }
        public String format { get; set; }
        public Time startTime { get; set; }
        public Datetime startDate { get; set; }
        public Datetime endDate { get; set; }
        public String image { get; set; }
        public String alt { get; set; }
        public Decimal ceus { get; set; }
        public String sponsor { get; set; }
        public Boolean featured { get; set; }
        public Date retireDate { get; set; }
        public Decimal cost { get; set; }
    }

    @HttpGet
    global static void getSummitEventsFeed() {
        feedType = RestContext.request.params.get('feedType');

        RestResponse res = RestContext.response;
        String callback = RestContext.request.params.get('callback');
        String serializedJSON = '';

        if (String.isBlank(callback)) {
            res.addHeader('Content-Type', 'application/json');
            callback = '';
        } else {
            res.addHeader('Content-Type', 'application/javascript');
        }

        if (feedType.toLowerCase() == 'courselist') {
            serializedJSON = JSON.serialize(getCapeItems());
            serializedJSON = serializedJSON.replace('"endDate":', '"end":');
        } else if (feedType.equalsIgnoreCase('parameterKey')) {
            serializedJSON = JSON.serialize(getParameterLists());
        }

        if (!String.isBlank(callback)) {
            serializedJSON = callback + '(' + serializedJSON + ')';
        }

        res.responseBody = Blob.valueOf(serializedJSON);
    }

    private static List<capeItem> getCapeItems() {
        List<capeItem> capeItemList = new List<capeItem>();
        RestRequest req = RestContext.request;
        String query = '';
        query += ' SELECT Id, Product2.Id, Product2.Name, Product2.Product_Description__c, Product2.Storefront_Info_Page__c, ' +
                ' Product2.Format__c, Product2.Start_Time__c, Product2.Course_Start_Date__c, Product2.Course_End_Date__c, ' +
                ' Product2.Course_Image__c, Product2.CEU_Amount__c, Product2.Sponsoring_College_School__c, ' +
                ' Product2.Featured_Course__c, Product2.Retire_Date__c, UnitPrice FROM PricebookEntry' +
                ' WHERE PriceBook2.IsStandard=true';

        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
        pricebookEntries = database.query(query);

        for (PricebookEntry entry : pricebookEntries) {
            capeItem cape = new capeItem();
            cape.id = entry.Product2.Id;
            cape.title = entry.Product2.Name;
            cape.link = entry.Product2.Storefront_Info_Page__c;
            cape.format = entry.Product2.Format__c;
            cape.startTime = entry.Product2.Start_Time__c;
            cape.startDate = entry.Product2.Course_Start_Date__c;
            cape.endDate = entry.Product2.Course_End_Date__c;
            cape.image = entry.Product2.Course_Image__c;
            cape.alt = entry.Product2.Name;
            cape.ceus = entry.Product2.CEU_Amount__c;
            cape.sponsor = entry.Product2.Sponsoring_College_School__c;
            cape.featured = entry.Product2.Featured_Course__c;
            cape.description = entry.Product2.Product_Description__c;
            cape.retireDate = entry.Product2.Retire_Date__c;
            cape.cost = entry.UnitPrice;
            capeItemList.add(cape);
        }

        return capeItemList;
    }

    private class parameterList {
        String parameter;
        String description;
        List<String> options;
    }

    private static List<parameterList> getParameterLists() {
        List<parameterList> allOptions = new List<parameterList>();
        return allOptions;
    }

}